:octocat: :wrench: Update actions-pin-version-setting-lint.yaml

diff --git a/.github/workflows/actions-pin-version-setting-lint.yaml b/.github/workflows/actions-pin-version-setting-lint.yaml
--- a/.github/workflows/actions-pin-version-setting-lint.yaml
+++ b/.github/workflows/actions-pin-version-setting-lint.yaml
@@ -21,6 +21,12 @@ on:
         type: string
         default: latest
 
+      fail-on-error:
+        description: "If it's to fail or not"
+        required: false
+        type: boolean
+        default: true
+
 jobs:
   lint:
     timeout-minutes: 10
@@ -142,3 +148,10 @@ jobs:
         run: |
           set -x
           reviewdog -f=diff -f.diff.strip=1 -name="gha-fix timeout" -reporter=github-pr-review -tee -filter-mode=nofilter < ${{ steps.timeout.outputs.diff_file }}
+
+      - name: Fail workflow
+        if: ${{ inputs.fail-on-error == 'true' }}
+        shell: bash
+        run: |
+          echo "::error ::Failure for found reviewdog install"
+          exit 1
